name: Bulletin
on:
  pull_request:
  push:
    branches:
      - main
      - 'renovate/*'
    paths:
      - 'packages/bulletin/**'
      - '.github/workflows/bulletin.yml'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))
    steps:
      - uses: actions/checkout@v6
      - run: yarn
      - run: yarn test:ci --theme bulletin
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v6
      - name: Deploy theme
        uses: TryGhost/action-deploy-theme@v1
        with:
          api-url: ${{ secrets.BULLETIN_GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.BULLETIN_GHOST_ADMIN_API_KEY }}
          working-directory: packages/bulletin
  subtree:
    name: Subtree
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: nxtlvlsoftware/git-subtree-action@1.1
        with:
          repo: 'TryGhost/Bulletin'
          path: 'packages/bulletin'
          deploy_key: ${{secrets.BULLETIN_GITHUB_DEPLOY_KEY}}
          force: true
