name: Edition
on:
  pull_request:
  push:
    branches:
      - main
      - 'renovate/*'
    paths:
      - 'packages/edition/**'
      - '.github/workflows/edition.yml'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))
    steps:
      - uses: actions/checkout@v4
      - run: yarn
      - run: yarn test:ci --theme edition
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy theme
        uses: TryGhost/action-deploy-theme@v1
        with:
          api-url: ${{ secrets.EDITION_GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.EDITION_GHOST_ADMIN_API_KEY }}
          working-directory: packages/edition
  subtree:
    name: Subtree
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: nxtlvlsoftware/git-subtree-action@1.1
        with:
          repo: 'TryGhost/Edition'
          path: 'packages/edition'
          deploy_key: ${{secrets.EDITION_GITHUB_DEPLOY_KEY}}
          force: true
