name: London
on:
  pull_request:
  push:
    branches:
      - main
      - 'renovate/*'
    paths:
      - 'themes/london/**'
      - '.github/workflows/london.yml'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn test:ci --theme london
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy theme
        uses: minimaluminium/action-deploy-theme@custom-dir
        with:
          api-url: ${{ secrets.LONDON_GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.LONDON_GHOST_ADMIN_API_KEY }}
          working-directory: themes/london
  subtree:
    name: Subtree
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nxtlvlsoftware/git-subtree-action@1.1
        with:
          repo: 'TryGhost/London'
          path: 'themes/london'
          deploy_key: ${{secrets.LONDON_GITHUB_DEPLOY_KEY}}
          force: true
